// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9in7sQL5BiKgsPuhcNAClJ98ckvQ23dw',
    appId: '1:1075771428579:web:bf494555e5a8f35978bfd6',
    messagingSenderId: '1075771428579',
    projectId: 'emptysaver-d27f2',
    authDomain: 'emptysaver-d27f2.firebaseapp.com',
    storageBucket: 'emptysaver-d27f2.appspot.com',
    measurementId: 'G-M98X5GK8SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVQYMlTDtuo3qLBzp1-xE2ZKU02An1fo',
    appId: '1:1075771428579:android:d6aafc9924a9aefc78bfd6',
    messagingSenderId: '1075771428579',
    projectId: 'emptysaver-d27f2',
    storageBucket: 'emptysaver-d27f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBGtevqbB3BkaMwD1wLsAj8v74xpVGX0',
    appId: '1:1075771428579:ios:b8a82acb3e4970ef78bfd6',
    messagingSenderId: '1075771428579',
    projectId: 'emptysaver-d27f2',
    storageBucket: 'emptysaver-d27f2.appspot.com',
    iosClientId: '1075771428579-ghrns15r6s27ungad1ldjq461ibej0cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptysaverFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBGtevqbB3BkaMwD1wLsAj8v74xpVGX0',
    appId: '1:1075771428579:ios:0d53bae3ab069d0078bfd6',
    messagingSenderId: '1075771428579',
    projectId: 'emptysaver-d27f2',
    storageBucket: 'emptysaver-d27f2.appspot.com',
    iosClientId: '1075771428579-ulg6rk28r9i591tu2uaiou6auocnhgv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.emptysaverFe.RunnerTests',
  );
}
